version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.5
    environment:
      - discovery.type=single-node

  logstash:
    image: logstash:7.17.5
    volumes:
      - ./logstash/logstash.conf:/usr/share/logstash/config/logstash.conf:ro
      - /var/log/sys
    depends_on:
      - elasticsearch

  kibana:
    container_name: kibana
    image: kibana:7.17.5
    # volumes:
    #   - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch